services:
  web:
    image: count-app:v4
    environment:
      - REDIS_HOST=mydb
      - REDIS_PORT=6379
    ports:
      - "5002:5002"
    deploy:
      replicas: 3
   
  mydb:
    image: redis:7
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
volumes:
  redis-data: